Update javadocCheckAction.yml

diff --git a/.github/workflows/javadocCheckAction.yml b/.github/workflows/javadocCheckAction.yml
--- a/.github/workflows/javadocCheckAction.yml
+++ b/.github/workflows/javadocCheckAction.yml
@@ -27,4 +27,5 @@ jobs:
       # Javadoc生成
       - name: Build javadoc
         run: |
-          echo `! ./gradlew javadoc`
+          echo `! ./gradlew javadoc 2>&1 | grep -v 'warning: \\[deprecation\\]' | grep -A 2 -e warning: -e error: ; exit $?`
+          ! ./gradlew javadoc 2>&1 | grep -v 'warning: \\[deprecation\\]' | grep -A 2 -e warning: -e error: ; exit $?
